import { FATHER_PHOTO } from './father-photo';

import {
  AdmissionApplication,
  ClassRoutineItem,
  DsheCategory,
  Exam,
  GrievanceTicket,
  Invoice,
  Notice,
  StudentExamResult,
  StudentProfile,
  Subject,
  TeacherProfile,
  User,
} from '../types';

export const SCHOOL_INFO = {
  nameEn: 'Harin Singha Adarsha High School',
  nameBn: 'হরিণ সিংহা আদর্শ উচ্চ বিদ্যালয়',
  eiin: '121123',
  mpoCode: '8702091302',
  boardEn: 'Dinajpur Education Board',
  boardBn: 'দিনাজপুর শিক্ষা বোর্ড',
  establishedDate: 'January 1, 1970',
  recognitionDate: 'January 1, 1972',
  landAreaTotalDecimals: 145,
  mainCampusFootprintDecimals: 40,
  buildingComplexSqFt: 5925,
  studentTeacherRatio: '38:1',
  studentClassroomRatio: '89:1',
  village: 'Harin Singha',
  villageBn: 'হরিণ সিংহা',
  union: 'Rahmatpur',
  unionBn: 'রহমতপুর',
  upazila: 'Gaibandha Sadar',
  upazilaBn: 'গাইবান্ধা সদর',
  district: 'Gaibandha',
  districtBn: 'গাইবান্ধা',
  division: 'Rangpur',
  divisionBn: 'রংপুর',
  postcode: '5700',
  phone: '+8801309-121123',
  email: 'hsahs121123@gmail.com',
  shifts: 'Single Shift (Morning to Afternoon)',
  type: 'Non-Government MPO Enrolled Secondary School (সহ-শিক্ষা)',
  academicGroups: ['Science', 'Humanities', 'Business Studies'],
  seatQuotas: {
    6: 130,
    7: 10,
    8: 10,
    '9-Science': 25,
    '9-Humanities': 5,
    '9-Business': 15,
    10: 40,
  },
  currentEnrolledCounts: {
    6: 118,
    7: 9,
    8: 8,
    '9-Science': 23,
    '9-Humanities': 4,
    '9-Business': 11,
    10: 36,
  },
};

export const INITIAL_USERS: User[] = [
  {
    id: 'user-admin-1',
    name: 'Md. Nazmul Haque Sarker',
    nameBn: 'মোঃ নাজমুল হক সরকার',
    email: 'headmaster@hsahs.edu.bd',
    role: 'ADMIN',
    phone: '+8801309-121123',
      },
  {
    id: 'user-teacher-1',
    name: 'Animesh Chandra Barman',
    nameBn: 'অনিমেষ চন্দ্র বর্মন',
    email: 'animesh.teacher@hsahs.edu.bd',
    role: 'TEACHER',
    phone: '+8801712-893452',
    associatedId: 'teacher-3',
      },
  {
    id: 'user-student-1',
    name: 'Sumaiya Akter Rimi',
    nameBn: 'সুমাইয়া আক্তার রিমি',
    email: 'sumaiya.601@hsahs.edu.bd',
    role: 'STUDENT',
    phone: '+8801719-450123',
    associatedId: 'student-1',
      },
];

export const INITIAL_TEACHERS: TeacherProfile[] = [
  {
    id: 'teacher-sajedur',
    name: 'Md. Sajedur Rahman',
    nameBn: 'মোঃ সাজেদুর রহমান',
    designation: 'Assistant Teacher',
    designationBn: 'সহকারী শিক্ষক',
    indexNumber: 'Not provided',
    mpoStatus: 'MPO Enrolled',
    mobile: '',
    email: '',
    subjectSpecialty: 'Agriculture Studies & Physical Education',
    subjectSpecialtyBn: 'কৃষি শিক্ষা ও শারীরিক শিক্ষা',
    joiningDate: 'Not provided',
    educationalQualification: 'Not provided',
    assignedClasses: [],
    assignedSubjects: ['Agriculture Studies', 'Physical Education'],
    avatarUrl: FATHER_PHOTO,
  },

  {
    id: 'teacher-head',
    name: 'Md. Nazmul Haque Sarker',
    nameBn: 'মোঃ নাজমুল হক সরকার',
    designation: 'Headmaster',
    designationBn: 'প্রধান শিক্ষক',
    indexNumber: '1048291',
    mpoStatus: 'MPO Enrolled',
    mobile: '+8801711-209841',
    email: 'headmaster@hsahs.edu.bd',
    subjectSpecialty: 'Mathematics & Educational Leadership',
    subjectSpecialtyBn: 'গণিত ও শিক্ষা প্রশাসন',
    joiningDate: '1998-03-15',
    educationalQualification: 'M.Sc (Mathematics), B.Ed (1st Class)',
    assignedClasses: [9, 10],
    assignedSubjects: ['Higher Mathematics'],
      },
  {
    id: 'teacher-1',
    name: 'Md. Shafiur Rahman',
    nameBn: 'মোঃ শফিউর রহমান',
    designation: 'Assistant Headmaster',
    designationBn: 'সহকারী প্রধান শিক্ষক',
    indexNumber: '1059382',
    mpoStatus: 'MPO Enrolled',
    mobile: '+8801718-493012',
    email: 'shafiur.rahman@hsahs.edu.bd',
    subjectSpecialty: 'English Language & Literature',
    subjectSpecialtyBn: 'ইংরেজি ভাষা ও সাহিত্য',
    joiningDate: '2001-08-01',
    educationalQualification: 'M.A (English), B.Ed',
    assignedClasses: [8, 9, 10],
    assignedSubjects: ['English 1st Paper', 'English 2nd Paper'],
      },
  {
    id: 'teacher-2',
    name: 'Md. Ehtashamul Hoque',
    nameBn: 'মোঃ এহতেশামুল হক',
    designation: 'Assistant Headmaster (Academic)',
    designationBn: 'সহকারী প্রধান শিক্ষক (একাডেমিক)',
    indexNumber: '1064719',
    mpoStatus: 'MPO Enrolled',
    mobile: '+8801723-559124',
    email: 'ehtashamul.hoque@hsahs.edu.bd',
    subjectSpecialty: 'General Science & Chemistry',
    subjectSpecialtyBn: 'সাধারণ বিজ্ঞান ও রসায়ন',
    joiningDate: '2003-04-12',
    educationalQualification: 'M.Sc (Chemistry), M.Ed',
    assignedClasses: [9, 10],
    assignedSubjects: ['Chemistry', 'General Science'],
      },
  {
    id: 'teacher-3',
    name: 'Animesh Chandra Barman',
    nameBn: 'অনিমেষ চন্দ্র বর্মন',
    designation: 'Senior Teacher',
    designationBn: 'সিনিয়র শিক্ষক',
    indexNumber: '1078234',
    mpoStatus: 'MPO Enrolled',
    mobile: '+8801712-893452',
    email: 'animesh.barman@hsahs.edu.bd',
    subjectSpecialty: 'General Mathematics & Physics',
    subjectSpecialtyBn: 'সাধারণ গণিত ও পদার্থবিজ্ঞান',
    joiningDate: '2006-02-18',
    educationalQualification: 'B.Sc (Hons), M.Sc (Physics), B.Ed',
    assignedClasses: [6, 7, 9],
    assignedSubjects: ['General Mathematics', 'Physics'],
      },
  {
    id: 'teacher-4',
    name: 'K.M. Sohag Rasul',
    nameBn: 'কে.এম. সোহাগ রসুল',
    designation: 'Assistant Teacher',
    designationBn: 'সহকারী শিক্ষক',
    indexNumber: '1091543',
    mpoStatus: 'MPO Enrolled',
    mobile: '+8801734-712890',
    email: 'sohag.rasul@hsahs.edu.bd',
    subjectSpecialty: 'Information & Communication Technology (ICT)',
    subjectSpecialtyBn: 'তথ্য ও যোগাযোগ প্রযুক্তি (আইসিটি)',
    joiningDate: '2013-09-01',
    educationalQualification: 'B.Sc (Computer Science & Engineering)',
    assignedClasses: [6, 7, 8, 9, 10],
    assignedSubjects: ['Information & Communication Technology'],
      },
  {
    id: 'teacher-5',
    name: 'Most. Dilruba Begum',
    nameBn: 'মোছাঃ দিলরুবা বেগম',
    designation: 'Senior Teacher',
    designationBn: 'সিনিয়র শিক্ষক',
    indexNumber: '1082910',
    mpoStatus: 'MPO Enrolled',
    mobile: '+8801715-620431',
    email: 'dilruba.begum@hsahs.edu.bd',
    subjectSpecialty: 'Bangla Literature & Grammar',
    subjectSpecialtyBn: 'বাংলা ভাষা ও ব্যাকরণ',
    joiningDate: '2007-06-10',
    educationalQualification: 'M.A (Bangla), B.Ed',
    assignedClasses: [6, 8, 9],
    assignedSubjects: ['Bangla 1st Paper', 'Bangla 2nd Paper'],
      },
  {
    id: 'teacher-6',
    name: 'Md. Abdur Rahim',
    nameBn: 'মোঃ আব্দুর রহিম',
    designation: 'Assistant Teacher (Social Science)',
    designationBn: 'সহকারী শিক্ষক (সামাজিক বিজ্ঞান)',
    indexNumber: '1098421',
    mpoStatus: 'MPO Enrolled',
    mobile: '+8801741-982103',
    email: 'abdur.rahim@hsahs.edu.bd',
    subjectSpecialty: 'Bangladesh & Global Studies, History',
    subjectSpecialtyBn: 'বাংলাদেশ ও বিশ্বপরিচয়, ইতিহাস',
    joiningDate: '2015-01-20',
    educationalQualification: 'M.S.S (Political Science), B.Ed',
    assignedClasses: [7, 8, 9, 10],
    assignedSubjects: ['Bangladesh & Global Studies', 'History'],
      },
];

export const INITIAL_STUDENTS: StudentProfile[] = [
  {
    id: 'student-1',
    studentId: 'HSAHS-2026-601',
    rollNumber: 1,
    name: 'Sumaiya Akter Rimi',
    nameBn: 'সুমাইয়া আক্তার রিমি',
    classLevel: 6,
    section: 'A',
    group: 'General',
    gender: 'Female',
    fatherName: 'Md. Rafiqul Islam',
    motherName: 'Salma Begum',
    guardianPhone: '+8801719-450123',
    dob: '2013-04-14',
    address: 'Harin Singha, Rahmatpur, Gaibandha Sadar',
    attendanceRate: 96,
  },
  {
    id: 'student-2',
    studentId: 'HSAHS-2026-602',
    rollNumber: 2,
    name: 'Tanvir Hossain Joy',
    nameBn: 'তানভীর হোসেন জয়',
    classLevel: 6,
    section: 'A',
    group: 'General',
    gender: 'Male',
    fatherName: 'Md. Abdul Jalil',
    motherName: 'Morium Begum',
    guardianPhone: '+8801728-112948',
    dob: '2013-07-22',
    address: 'Balia, Rahmatpur Union, Gaibandha Sadar',
    attendanceRate: 92,
  },
  {
    id: 'student-3',
    studentId: 'HSAHS-2026-901',
    rollNumber: 1,
    name: 'Fahim Shahriar',
    nameBn: 'ফাহিম শাহরিয়ার',
    classLevel: 9,
    section: 'A',
    group: 'Science',
    gender: 'Male',
    fatherName: 'Md. Shah Alam',
    motherName: 'Nasrin Sultana',
    guardianPhone: '+8801712-409182',
    dob: '2010-09-05',
    address: 'Harin Singha, Rahmatpur Union, Gaibandha',
    attendanceRate: 98,
  },
  {
    id: 'student-4',
    studentId: 'HSAHS-2026-902',
    rollNumber: 2,
    name: 'Nusrat Jahan Mim',
    nameBn: 'নুসরাত জাহান মিম',
    classLevel: 9,
    section: 'A',
    group: 'Science',
    gender: 'Female',
    fatherName: 'Md. Mokhlesur Rahman',
    motherName: 'Fatema Khatun',
    guardianPhone: '+8801735-882019',
    dob: '2010-12-11',
    address: 'Kholabari, Rahmatpur, Gaibandha Sadar',
    attendanceRate: 94,
  },
  {
    id: 'student-5',
    studentId: 'HSAHS-2026-910',
    rollNumber: 10,
    name: 'Md. Shakil Mia',
    nameBn: 'মোঃ শাকিল মিঞা',
    classLevel: 9,
    section: 'B',
    group: 'Humanities',
    gender: 'Male',
    fatherName: 'Md. Rostom Ali',
    motherName: 'Halima Begum',
    guardianPhone: '+8801744-129840',
    dob: '2010-02-18',
    address: 'Purba Harin Singha, Gaibandha',
    attendanceRate: 88,
  },
  {
    id: 'student-6',
    studentId: 'HSAHS-2026-1001',
    rollNumber: 1,
    name: 'Mehedi Hasan Niloy',
    nameBn: 'মেহেদী হাসান নিলয়',
    classLevel: 10,
    section: 'A',
    group: 'Science',
    gender: 'Male',
    fatherName: 'Md. Golam Sarwar',
    motherName: 'Rokeya Begum',
    guardianPhone: '+8801716-901452',
    dob: '2009-05-19',
    address: 'Balia, Rahmatpur, Gaibandha',
    attendanceRate: 95,
  },
];

export const INITIAL_SUBJECTS: Subject[] = [
  // Class 6 Subjects
  { id: 'sub-6-1', code: '101', name: 'Bangla', nameBn: 'বাংলা', classLevel: 6, group: 'General', isOptional: false, fullMarks: 100, passMarks: 33 },
  { id: 'sub-6-2', code: '107', name: 'English', nameBn: 'ইংরেজি', classLevel: 6, group: 'General', isOptional: false, fullMarks: 100, passMarks: 33 },
  { id: 'sub-6-3', code: '109', name: 'Mathematics', nameBn: 'গণিত', classLevel: 6, group: 'General', isOptional: false, fullMarks: 100, passMarks: 33 },
  { id: 'sub-6-4', code: '127', name: 'General Science', nameBn: 'বিজ্ঞান', classLevel: 6, group: 'General', isOptional: false, fullMarks: 100, passMarks: 33 },
  { id: 'sub-6-5', code: '150', name: 'Bangladesh & Global Studies', nameBn: 'বাংলাদেশ ও বিশ্বপরিচয়', classLevel: 6, group: 'General', isOptional: false, fullMarks: 100, passMarks: 33 },
  { id: 'sub-6-6', code: '111', name: 'Islam & Moral Education', nameBn: 'ইসলাম ও নৈতিক শিক্ষা', classLevel: 6, group: 'General', isOptional: false, fullMarks: 100, passMarks: 33 },
  { id: 'sub-6-7', code: '154', name: 'Information & Communication Tech (ICT)', nameBn: 'তথ্য ও যোগাযোগ প্রযুক্তি', classLevel: 6, group: 'General', isOptional: false, fullMarks: 100, passMarks: 33 },
  { id: 'sub-6-8', code: '134', name: 'Agriculture Studies (4th Subject)', nameBn: 'কৃষি শিক্ষা (৪র্থ বিষয়)', classLevel: 6, group: 'General', isOptional: true, fullMarks: 100, passMarks: 33 },

  // Class 9 Science Subjects
  { id: 'sub-9-1', code: '101', name: 'Bangla (101/102)', nameBn: 'বাংলা', classLevel: 9, group: 'Science', isOptional: false, fullMarks: 100, passMarks: 33 },
  { id: 'sub-9-2', code: '107', name: 'English (107/108)', nameBn: 'ইংরেজি', classLevel: 9, group: 'Science', isOptional: false, fullMarks: 100, passMarks: 33 },
  { id: 'sub-9-3', code: '109', name: 'General Mathematics', nameBn: 'সাধারণ গণিত', classLevel: 9, group: 'Science', isOptional: false, fullMarks: 100, passMarks: 33 },
  { id: 'sub-9-4', code: '111', name: 'Religion & Moral Education', nameBn: 'ধর্ম ও নৈতিক শিক্ষা', classLevel: 9, group: 'Science', isOptional: false, fullMarks: 100, passMarks: 33 },
  { id: 'sub-9-5', code: '154', name: 'ICT', nameBn: 'আইসিটি', classLevel: 9, group: 'Science', isOptional: false, fullMarks: 100, passMarks: 33 },
  { id: 'sub-9-6', code: '150', name: 'Bangladesh & Global Studies', nameBn: 'বাংলাদেশ ও বিশ্বপরিচয়', classLevel: 9, group: 'Science', isOptional: false, fullMarks: 100, passMarks: 33 },
  { id: 'sub-9-7', code: '136', name: 'Physics', nameBn: 'পদার্থবিজ্ঞান', classLevel: 9, group: 'Science', isOptional: false, fullMarks: 100, passMarks: 33 },
  { id: 'sub-9-8', code: '137', name: 'Chemistry', nameBn: 'রসায়ন', classLevel: 9, group: 'Science', isOptional: false, fullMarks: 100, passMarks: 33 },
  { id: 'sub-9-9', code: '138', name: 'Biology', nameBn: 'জীববিজ্ঞান', classLevel: 9, group: 'Science', isOptional: false, fullMarks: 100, passMarks: 33 },
  { id: 'sub-9-10', code: '126', name: 'Higher Mathematics (Optional 4th)', nameBn: 'উচ্চতর গণিত (৪র্থ বিষয়)', classLevel: 9, group: 'Science', isOptional: true, fullMarks: 100, passMarks: 33 },
];

export const INITIAL_EXAMS: Exam[] = [
  {
    id: 'exam-2026-annual',
    title: 'Annual Examination 2026',
    titleBn: 'বার্ষিক পরীক্ষা ২০২৬',
    sessionYear: 2026,
    term: 'Annual',
    isPublished: true,
    publishedAt: '2026-10-01',
  },
  {
    id: 'exam-2026-half',
    title: 'Half-Yearly Examination 2026',
    titleBn: 'অর্ধ-বার্ষিক পরীক্ষা ২০২৬',
    sessionYear: 2026,
    term: 'Half-Yearly',
    isPublished: true,
    publishedAt: '2026-06-25',
  },
];

export const INITIAL_RESULTS: StudentExamResult[] = [
  {
    id: 'res-601',
    studentId: 'student-1',
    examId: 'exam-2026-annual',
    sessionYear: 2026,
    classLevel: 6,
    section: 'A',
    rollNumber: 1,
    studentName: 'Sumaiya Akter Rimi',
    studentNameBn: 'সুমাইয়া আক্তার রিমি',
    marks: [
      { subjectId: 'sub-6-1', subjectName: 'Bangla', subjectCode: '101', isOptional: false, writtenMarks: 58, mcqMarks: 27, practicalMarks: 0, totalMarks: 85, letterGrade: 'A+', gradePoint: 5.0 },
      { subjectId: 'sub-6-2', subjectName: 'English', subjectCode: '107', isOptional: false, writtenMarks: 82, mcqMarks: 0, practicalMarks: 0, totalMarks: 82, letterGrade: 'A+', gradePoint: 5.0 },
      { subjectId: 'sub-6-3', subjectName: 'Mathematics', subjectCode: '109', isOptional: false, writtenMarks: 60, mcqMarks: 29, practicalMarks: 0, totalMarks: 89, letterGrade: 'A+', gradePoint: 5.0 },
      { subjectId: 'sub-6-4', subjectName: 'General Science', subjectCode: '127', isOptional: false, writtenMarks: 54, mcqMarks: 28, practicalMarks: 0, totalMarks: 82, letterGrade: 'A+', gradePoint: 5.0 },
      { subjectId: 'sub-6-5', subjectName: 'BGS', subjectCode: '150', isOptional: false, writtenMarks: 55, mcqMarks: 25, practicalMarks: 0, totalMarks: 80, letterGrade: 'A+', gradePoint: 5.0 },
      { subjectId: 'sub-6-6', subjectName: 'Islam Education', subjectCode: '111', isOptional: false, writtenMarks: 59, mcqMarks: 29, practicalMarks: 0, totalMarks: 88, letterGrade: 'A+', gradePoint: 5.0 },
      { subjectId: 'sub-6-7', subjectName: 'ICT', subjectCode: '154', isOptional: false, writtenMarks: 20, mcqMarks: 25, practicalMarks: 46, totalMarks: 91, letterGrade: 'A+', gradePoint: 5.0 },
      { subjectId: 'sub-6-8', subjectName: 'Agriculture Studies (4th)', subjectCode: '134', isOptional: true, writtenMarks: 50, mcqMarks: 22, practicalMarks: 18, totalMarks: 90, letterGrade: 'A+', gradePoint: 5.0 },
    ],
    totalMarksObtained: 687,
    gpa: 5.0,
    letterGrade: 'A+',
    hasFailed: false,
    fourthSubjectBonus: 3.0,
    meritPosition: 1,
    remarks: 'Outstanding (Golden A+)',
    publishedDate: '2026-10-01',
  },
  {
    id: 'res-901',
    studentId: 'student-3',
    examId: 'exam-2026-annual',
    sessionYear: 2026,
    classLevel: 9,
    section: 'A',
    rollNumber: 1,
    studentName: 'Fahim Shahriar',
    studentNameBn: 'ফাহিম শাহরিয়ার',
    marks: [
      { subjectId: 'sub-9-1', subjectName: 'Bangla', subjectCode: '101', isOptional: false, writtenMarks: 56, mcqMarks: 26, practicalMarks: 0, totalMarks: 82, letterGrade: 'A+', gradePoint: 5.0 },
      { subjectId: 'sub-9-2', subjectName: 'English', subjectCode: '107', isOptional: false, writtenMarks: 78, mcqMarks: 0, practicalMarks: 0, totalMarks: 78, letterGrade: 'A', gradePoint: 4.0 },
      { subjectId: 'sub-9-3', subjectName: 'General Math', subjectCode: '109', isOptional: false, writtenMarks: 60, mcqMarks: 30, practicalMarks: 0, totalMarks: 90, letterGrade: 'A+', gradePoint: 5.0 },
      { subjectId: 'sub-9-4', subjectName: 'Religion', subjectCode: '111', isOptional: false, writtenMarks: 57, mcqMarks: 28, practicalMarks: 0, totalMarks: 85, letterGrade: 'A+', gradePoint: 5.0 },
      { subjectId: 'sub-9-5', subjectName: 'ICT', subjectCode: '154', isOptional: false, writtenMarks: 20, mcqMarks: 24, practicalMarks: 45, totalMarks: 89, letterGrade: 'A+', gradePoint: 5.0 },
      { subjectId: 'sub-9-6', subjectName: 'BGS', subjectCode: '150', isOptional: false, writtenMarks: 50, mcqMarks: 25, practicalMarks: 0, totalMarks: 75, letterGrade: 'A', gradePoint: 4.0 },
      { subjectId: 'sub-9-7', subjectName: 'Physics', subjectCode: '136', isOptional: false, writtenMarks: 45, mcqMarks: 20, practicalMarks: 23, totalMarks: 88, letterGrade: 'A+', gradePoint: 5.0 },
      { subjectId: 'sub-9-8', subjectName: 'Chemistry', subjectCode: '137', isOptional: false, writtenMarks: 46, mcqMarks: 21, practicalMarks: 24, totalMarks: 91, letterGrade: 'A+', gradePoint: 5.0 },
      { subjectId: 'sub-9-9', subjectName: 'Biology', subjectCode: '138', isOptional: false, writtenMarks: 44, mcqMarks: 20, practicalMarks: 22, totalMarks: 86, letterGrade: 'A+', gradePoint: 5.0 },
      { subjectId: 'sub-9-10', subjectName: 'Higher Math (4th)', subjectCode: '126', isOptional: true, writtenMarks: 48, mcqMarks: 22, practicalMarks: 24, totalMarks: 94, letterGrade: 'A+', gradePoint: 5.0 },
    ],
    totalMarksObtained: 858,
    gpa: 5.0,
    letterGrade: 'A+',
    hasFailed: false,
    fourthSubjectBonus: 3.0,
    meritPosition: 1,
    remarks: 'Outstanding (Golden A+)',
    publishedDate: '2026-10-01',
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-101',
    invoiceNumber: 'INV-2026-10482',
    studentId: 'student-1',
    studentName: 'Sumaiya Akter Rimi',
    classLevel: 6,
    rollNumber: 1,
    title: 'Monthly Tuition Fee - October 2026',
    titleBn: 'মাসিক বেতন - অক্টোবর ২০২৬',
    description: 'Regular academic session monthly tuition fee for Class 6',
    amount: 350,
    dueDate: '2026-10-25',
    status: 'UNPAID',
  },
  {
    id: 'inv-102',
    invoiceNumber: 'INV-2026-10390',
    studentId: 'student-1',
    studentName: 'Sumaiya Akter Rimi',
    classLevel: 6,
    rollNumber: 1,
    title: 'Annual Examination Fee 2026',
    titleBn: 'বার্ষিক পরীক্ষা ফি ২০২৬',
    description: 'Question papers, answer scripts, and center fee',
    amount: 450,
    dueDate: '2026-09-30',
    status: 'PAID',
    paymentMethod: 'bKash',
    paymentId: 'TRX_BK_791823_10192',
    transactionId: 'BK2610781290',
    paidAt: '2026-09-28 11:42 AM',
    senderPhone: '01719450123',
  },
  {
    id: 'inv-103',
    invoiceNumber: 'INV-2026-10483',
    studentId: 'student-1',
    studentName: 'Sumaiya Akter Rimi',
    classLevel: 6,
    rollNumber: 1,
    title: 'ICT Lab & Sports Facility Development',
    titleBn: 'আইসিটি ল্যাব ও ক্রীড়া উন্নয়ন ফি',
    description: 'Annual computer laboratory maintenance and scout fee',
    amount: 200,
    dueDate: '2026-10-31',
    status: 'UNPAID',
  },
  {
    id: 'inv-104',
    invoiceNumber: 'INV-2026-10484',
    studentId: 'student-3',
    studentName: 'Fahim Shahriar',
    classLevel: 9,
    rollNumber: 1,
    title: 'Science Laboratory & Practical Fee (Term 2)',
    titleBn: 'বিজ্ঞান ল্যাবরেটরি ও ব্যবহারিক ফি',
    description: 'Chemistry, Physics, and Biology laboratory consumables',
    amount: 500,
    dueDate: '2026-10-20',
    status: 'UNPAID',
  },
];

export const INITIAL_NOTICES: Notice[] = [
  {
    id: 'not-1',
    title: 'Official Publication of Annual Examination 2026 Schedule & Guidelines',
    titleBn: '২০২৬ সালের বার্ষিক পরীক্ষার রুটিন ও নির্দেশনা প্রকাশ প্রসঙ্গে',
    content: 'All students and respected guardians are hereby notified that the Annual Examination 2026 of Harin Singha Adarsha High School will commence on 12th November 2026 according to the standard Dinajpur Board academic calendar. Please clear outstanding session dues by 30th October 2026 to receive admit cards.',
    contentBn: 'এতদ্বারা হরিণ সিংহা আদর্শ উচ্চ বিদ্যালয়ের সকল শিক্ষার্থী ও সম্মানিত অভিভাবকদের জানানো যাচ্ছে যে, দিনাজপুর শিক্ষা বোর্ডের একাডেমিক ক্যালেন্ডার অনুযায়ী ২০২৬ সালের বার্ষিক পরীক্ষা আগামী ১২ই নভেম্বর ২০২৬ তারিখ হতে শুরু হবে। ৩০শে অক্টোবরের মধ্যে সকল প্রকার বকেয়া পরিশোধপূর্বক প্রবেশপত্র সংগ্রহ করার জন্য অনুরোধ করা হলো।',
    category: 'Exam',
    publishedAt: '2026-10-04',
    isFeatured: true,
    pdfAttachment: 'HSAHS_Annual_Exam_Routine_2026.pdf',
    author: 'Headmaster',
  },
  {
    id: 'not-2',
    title: 'Online Admission Notice for Academic Session 2027 (Class 6 to 9)',
    titleBn: '২০২৭ শিক্ষাবর্ষে ৬ষ্ঠ থেকে ৯ম শ্রেণিতে অনলাইন ভর্তি আবেদন বিজ্ঞপ্তি',
    content: 'Online admission applications are now open for the 2027 academic year. Authorized intake quotas: Class 6 (130 seats), Class 7 (10 seats), Class 8 (10 seats), Class 9 Science (25 seats), Class 9 Humanities (5 seats). Apply through our official digital portal without visiting the physical campus.',
    contentBn: '২০২৭ শিক্ষাবর্ষে ৬ষ্ঠ থেকে ৯ম শ্রেণিতে সরকারি নীতিমালা অনুযায়ী অনলাইন ভর্তি আবেদন কার্যক্রম শুরু হয়েছে। আসন সংখ্যা: ৬ষ্ঠ শ্রেণি (১৩০), ৭ম শ্রেণি (১০), ৮ম শ্রেণি (১০), ৯ম বিজ্ঞান (২৫), ৯ম মানবিক (৫)। বিদ্যালয়ের ওয়েব পোর্টাল হতে সরাসরি আবেদন করা যাবে।',
    category: 'Academic',
    publishedAt: '2026-10-02',
    isFeatured: true,
    pdfAttachment: 'Admission_Circular_2027_HSAHS.pdf',
    author: 'Admission Committee',
  },
  {
    id: 'not-3',
    title: 'DSHE EMIS Institutional Web Verification Directive Adherence',
    titleBn: 'মাউশি ইএমআইএস প্রাতিষ্ঠানিক ওয়েব পোর্টাল যাচাইকরণ ও তথ্য হালনাগাদ',
    content: 'In compliance with the Directorate of Secondary and Higher Education (DSHE) and Dinajpur Education Board, the 11-point statutory transparency framework has been fully deployed on this portal for government inspection and public verification.',
    contentBn: 'মাধ্যমিক ও উচ্চশিক্ষা অধিদপ্তর (মাউশি) এবং দিনাজপুর শিক্ষা বোর্ডের নির্দেশনা মোতাবেক অত্র বিদ্যালয়ের ১১ দফা সংবিধিবদ্ধ তথ্য ও এমআইএস ডাটাবেজ ডিজিটাল পোর্টালে জনসাধারণের যাচাইয়ের জন্য উন্মুক্ত করা হলো।',
    category: 'Administrative',
    publishedAt: '2026-09-28',
    isFeatured: false,
    author: 'Assistant Headmaster',
  },
  {
    id: 'not-4',
    title: 'Special Extra Coaching Classes for SSC 2027 Examinees (Class 10)',
    titleBn: 'এসএসসি ২০২৭ পরীক্ষার্থীদের জন্য বিশেষ প্রস্তুতিমূলক ক্লাস সংক্রান্ত',
    content: 'Extra remedial classes in Higher Math, English, and Physics will be held every Saturday from 9:00 AM to 12:30 PM for all registered Class 10 candidates.',
    contentBn: '২০২৭ সালের এসএসসি পরীক্ষার্থীদের জন্য প্রতি শনিবার সকাল ৯:০০ টা হতে দুপুর ১২:৩০ টা পর্যন্ত উচ্চতর গণিত, ইংরেজি ও পদার্থবিজ্ঞান বিষয়ের বিশেষ প্রস্তুতিমূলক ক্লাস অনুষ্ঠিত হবে।',
    category: 'Routine',
    publishedAt: '2026-09-20',
    isFeatured: false,
    author: 'Academic Council',
  },
];

export const INITIAL_ADMISSIONS: AdmissionApplication[] = [
  {
    id: 'adm-01',
    applicationToken: 'ADM-2027-6001',
    applicantName: 'Muntaha Islam',
    applicantNameBn: 'মুনতাহা ইসলাম',
    appliedClass: 6,
    appliedGroup: 'General',
    gender: 'Female',
    dob: '2014-03-12',
    fatherName: 'Md. Shafiqul Islam',
    motherName: 'Mahmuda Begum',
    guardianMobile: '+8801712-998877',
    previousSchool: 'Harin Singha Government Primary School',
    previousPecOrJscGpa: 5.0,
    quotaCategory: 'Catchment Area',
    submissionDate: '2026-10-03',
    status: 'ACCEPTED',
    assignedRoll: 119,
    assignedSection: 'A',
  },
  {
    id: 'adm-02',
    applicationToken: 'ADM-2027-6002',
    applicantName: 'Abu Bakar Siddique',
    applicantNameBn: 'আবু বকর সিদ্দিক',
    appliedClass: 6,
    appliedGroup: 'General',
    gender: 'Male',
    dob: '2014-06-25',
    fatherName: 'Md. Enamul Haque',
    motherName: 'Sabina Yasmin',
    guardianMobile: '+8801723-445566',
    previousSchool: 'Rahmatpur Government Primary School',
    previousPecOrJscGpa: 4.8,
    quotaCategory: 'General',
    submissionDate: '2026-10-04',
    status: 'PENDING',
  },
  {
    id: 'adm-03',
    applicationToken: 'ADM-2027-9001',
    applicantName: 'Shahriar Kabir',
    applicantNameBn: 'শাহরিয়ার কবির',
    appliedClass: 9,
    appliedGroup: 'Science',
    gender: 'Male',
    dob: '2011-01-10',
    fatherName: 'Md. Lutfor Rahman',
    motherName: 'Shahnaz Parveen',
    guardianMobile: '+8801733-112233',
    previousSchool: 'Harin Singha Adarsha High School (Class 8)',
    previousPecOrJscGpa: 5.0,
    quotaCategory: 'General',
    submissionDate: '2026-10-05',
    status: 'ACCEPTED',
    assignedRoll: 24,
    assignedSection: 'A',
  },
];

export const INITIAL_GRIEVANCES: GrievanceTicket[] = [
  {
    id: 'grv-1',
    trackingCode: 'GRS-2026-081',
    submitterName: 'Md. Abdus Samad',
    submitterRole: 'Parent',
    contactPhone: '+8801718-223344',
    email: 'samad.gaibandha@gmail.com',
    subject: 'Request for clean drinking water filter installation in South Academic Block',
    description: 'During summer and sunny noon periods, students on the 1st floor of the South building face difficulties finding pure drinking water. Kindly set up an additional arsenic-tested filtration unit.',
    submittedAt: '2026-09-25',
    status: 'RESOLVED',
    adminResolution: 'A modern 4-stage UV water filtration system has been installed on the first floor veranda near Room 104 on 28th September 2026.',
    resolvedAt: '2026-09-28',
  },
  {
    id: 'grv-2',
    trackingCode: 'GRS-2026-094',
    submitterName: 'Rashedul Karim',
    submitterRole: 'Parent',
    contactPhone: '+8801715-998811',
    subject: 'Request for additional boundary lighting on the road adjacent to the school pond',
    description: 'During winter evenings when students return from coaching classes, the road along the eastern 40-decimal boundary lacks sufficient street lighting.',
    submittedAt: '2026-10-02',
    status: 'UNDER_INVESTIGATION',
    adminResolution: 'Matter forwarded to the School Managing Committee infrastructure wing. 2 solar LED posts will be deployed by mid-October.',
  },
];

export const MANAGING_COMMITTEE = [
  { name: 'Alhaj Md. Mokhlesur Rahman', nameBn: 'আলহাজ্ব মোঃ মোখলেসুর রহমান', designation: 'President / সভাপতি', tenure: '2024 - 2027', occupation: 'Social Worker & Philanthropist', phone: '+8801711-300401' },
  { name: 'Md. Nazmul Haque Sarker', nameBn: 'মোঃ নাজমুল হক সরকার', designation: 'Member Secretary (Headmaster) / সদস্য সচিব (প্রধান শিক্ষক)', tenure: 'Ex-Officio', occupation: 'Institutional Head', phone: '+8801711-209841' },
  { name: 'Md. Shafiur Rahman', nameBn: 'মোঃ শফিউর রহমান', designation: 'Teacher Representative / শিক্ষক প্রতিনিধি', tenure: '2024 - 2026', occupation: 'Assistant Headmaster', phone: '+8801718-493012' },
  { name: 'Most. Dilruba Begum', nameBn: 'মোছাঃ দিলরুবা বেগম', designation: 'Female Teacher Representative / সংরক্ষিত মহিলা শিক্ষক প্রতিনিধি', tenure: '2024 - 2026', occupation: 'Senior Teacher', phone: '+8801715-620431' },
  { name: 'Md. Rafiqul Islam', nameBn: 'মোঃ রফিকুল ইসলাম', designation: 'Guardian Member / অভিভাবক সদস্য (সাধারণ)', tenure: '2024 - 2026', occupation: 'Businessman', phone: '+8801719-450123' },
  { name: 'Begum Rokeya Akter', nameBn: 'বেগম রোকেয়া আক্তার', designation: 'Female Guardian Member / সংরক্ষিত মহিলা অভিভাবক সদস্য', tenure: '2024 - 2026', occupation: 'Education Enthusiast', phone: '+8801728-990011' },
  { name: 'Prof. Golam Mortuza', nameBn: 'প্রফেসর গোলাম মর্তুজা', designation: 'Educationist Representative / শিক্ষানুরাগী সদস্য', tenure: '2024 - 2027', occupation: 'Retired College Principal', phone: '+8801714-556677' },
  { name: 'Upazila Secondary Education Officer', nameBn: 'উপজেলা মাধ্যমিক শিক্ষা অফিসার, গাইবান্ধা সদর', designation: 'Government Representative / সরকারি প্রতিনিধি', tenure: 'Permanent Ex-Officio', occupation: 'DSHE Official', phone: '+880541-61234' },
];

export const CITIZEN_CHARTER = [
  { serviceNameEn: 'Issuance of Transfer Certificate (TC)', serviceNameBn: 'ছাড়পত্র (টিসি) প্রদান', timeLimitEn: 'Within 2 working days', timeLimitBn: '২ কর্মদিবসের মধ্যে', feeEn: 'BDT 150', feeBn: '১৫০ টাকা', officerEn: 'Assistant Headmaster' },
  { serviceNameEn: 'Character & Testimonial Certificate', serviceNameBn: 'প্রশংসাপত্র / চারিত্রিক সনদ প্রদান', timeLimitEn: 'Within 1 working day', timeLimitBn: '১ কর্মদিবসের মধ্যে', feeEn: 'BDT 100', feeBn: '১০০ টাকা', officerEn: 'Headmaster' },
  { serviceNameEn: 'Academic Transcript & Marks Verification', serviceNameBn: 'নম্বরপত্র ও ফলাফল সত্যায়ন', timeLimitEn: 'Instant (Via Web) / 1 Day', timeLimitBn: 'অনলাইনে তাৎক্ষণিক / ১ দিন', feeEn: 'Free / BDT 50', feeBn: 'বিনামূল্যে / ৫০ টাকা', officerEn: 'ICT In-Charge' },
  { serviceNameEn: 'Online Admission Application Processing', serviceNameBn: 'ভর্তি আবেদন ও তথ্য যাচাই', timeLimitEn: 'Instant Token Generation', timeLimitBn: 'তাৎক্ষণিক টোকেন প্রদান', feeEn: 'BDT 100', feeBn: '১০০ টাকা', officerEn: 'Admission Committee' },
  { serviceNameEn: 'Grievance Redress & Complaint Resolution', serviceNameBn: 'অভিযোগ প্রতিকার নিষ্পত্তি', timeLimitEn: 'Within 7 working days', timeLimitBn: '৭ কর্মদিবসের মধ্যে', feeEn: 'Free of Cost', feeBn: 'বিনামূল্যে', officerEn: 'Grievance Redress Officer (GRO)' },
  { serviceNameEn: 'Stipend & Upazila Scholarship Processing', serviceNameBn: 'উপবৃত্তি ও মেধাভিত্তিক বৃত্তি সংক্রান্ত সেবা', timeLimitEn: 'Within 3 working days', timeLimitBn: '৩ কর্মদিবসের মধ্যে', feeEn: 'Free of Cost', feeBn: 'বিনামূল্যে', officerEn: 'Accounts Officer' },
];

export const DSHE_COMPLIANCE_CATEGORIES: DsheCategory[] = [
  {
    key: 'history-overview',
    number: 1,
    titleEn: '1. Institutional Overview & History',
    titleBn: '১. প্রাতিষ্ঠানিক পরিচিতি ও গৌরবোজ্জ্বল ইতিহাস',
    summaryEn: 'Foundation, location, 145-decimal campus, 5,925 sq ft infrastructure, vision and mission.',
    summaryBn: 'প্রতিষ্ঠা, অবস্থান, ১৪৫ শতাংশ ভূমিসম্পদ, ৫,৯২৫ বর্গফুট ভবন অবকাঠামো ও রূপকল্প।',
    dataItems: [
      { labelEn: 'Institution Name', labelBn: 'প্রতিষ্ঠানের নাম', valueEn: 'Harin Singha Adarsha High School', valueBn: 'হরিণ সিংহা আদর্শ উচ্চ বিদ্যালয়' },
      { labelEn: 'Founding Date', labelBn: 'প্রতিষ্ঠা সাল', valueEn: 'January 1, 1970 (Established)', valueBn: '১ জানুয়ারি ১৯৭০ খ্রি.' },
      { labelEn: 'Total Land Area', labelBn: 'মোট জমির পরিমাণ', valueEn: '145 Decimals (শতক)', valueBn: '১৪৫ শতক (১.৪৫ একর)' },
      { labelEn: 'Main Campus Footprint', labelBn: 'মূল ক্যাম্পাস এলাকা', valueEn: '40 Decimals', valueBn: '৪০ শতক' },
      { labelEn: 'Structural Building Area', labelBn: 'পাকা ভবন আয়তন', valueEn: '5,925 Square Feet', valueBn: '৫,৯২৫ বর্গফুট' },
      { labelEn: 'Student-Teacher Ratio', labelBn: 'শিক্ষার্থী-শিক্ষক অনুপাত', valueEn: '38:1 (Benchmark compliant)', valueBn: '৩৮:১' },
      { labelEn: 'Student-Classroom Ratio', labelBn: 'শিক্ষার্থী-শ্রেণিকক্ষ অনুপাত', valueEn: '89:1', valueBn: '৮৯:১' },
      { labelEn: 'Administrative Jurisdiction', labelBn: 'প্রশাসনিক এখতিয়ার', valueEn: 'Rahmatpur Union, Gaibandha Sadar, Rangpur Division', valueBn: 'রহমতপুর ইউনিয়ন, গাইবান্ধা সদর, রংপুর বিভাগ' },
    ],
    pdfDocuments: [
      { name: 'HSAHS_Institutional_Master_Brochure_2026.pdf', fileSize: '2.4 MB', downloadUrl: '#' },
      { name: 'Land_Deed_Khatiyan_145_Decimals.pdf', fileSize: '1.8 MB', downloadUrl: '#' },
    ],
  },
  {
    key: 'board-recognition',
    number: 2,
    titleEn: '2. Academic Approval & Recognition',
    titleBn: '২. শিক্ষা বোর্ড একাডেমিক স্বীকৃতি ও অনুমোদন',
    summaryEn: 'Secondary academic recognition under Dinajpur Education Board, teaching permission letters.',
    summaryBn: 'দিনাজপুর শিক্ষা বোর্ডের অধীনে মাধ্যমিক স্বীকৃতি ও পাঠদানের সরকারি অনুমোদনপত্র।',
    dataItems: [
      { labelEn: 'Educational Board', labelBn: 'শিক্ষা বোর্ড', valueEn: 'Dinajpur Education Board', valueBn: 'দিনাজপুর শিক্ষা বোর্ড', badge: 'Active Board Jurisdiction' },
      { labelEn: 'First Board Recognition', labelBn: 'বোর্ড স্বীকৃতির তারিখ', valueEn: 'January 1, 1972', valueBn: '১ জানুয়ারি ১৯৭২ খ্রি.' },
      { labelEn: 'Academic Level Recognized', labelBn: 'স্বীকৃত স্তর', valueEn: 'Secondary (Class 6 - 10)', valueBn: 'মাধ্যমিক (৬ষ্ঠ - ১০ম শ্রেণি)' },
      { labelEn: 'Offered Streams / Groups', labelBn: 'অনুমোদিত বিভাগসমূহ', valueEn: 'Science, Humanities, Business Studies', valueBn: 'বিজ্ঞান, মানবিক ও ব্যবসায় শিক্ষা' },
      { labelEn: 'Recognition Renewal Status', labelBn: 'স্বীকৃতি নবায়ন স্থিতি', valueEn: 'Valid & Permanently Enrolled', valueBn: 'নবায়িত ও স্থায়ীভাবে কার্যকর' },
    ],
    pdfDocuments: [
      { name: 'Dinajpur_Board_Secondary_Recognition_Order_1972.pdf', fileSize: '1.2 MB', downloadUrl: '#' },
      { name: 'DSHE_Teaching_Permission_Circular.pdf', fileSize: '850 KB', downloadUrl: '#' },
    ],
  },
  {
    key: 'student-demographics',
    number: 3,
    titleEn: '3. Student Demographics & Statistics',
    titleBn: '৩. শ্রেণিভিত্তিক শিক্ষার্থী পরিসংখ্যান ও লিঙ্গভিত্তিক অনুপাত',
    summaryEn: 'Live breakdown of enrolled learners by class, section, group, and gender.',
    summaryBn: 'শ্রেণি, শাখা, বিভাগ ও লিঙ্গভিত্তিক শিক্ষার্থীদের হালনাগাদ পরিসংখ্যান।',
    dataItems: [
      { labelEn: 'Total Enrolled Learners', labelBn: 'মোট অধ্যয়নরত শিক্ষার্থী', valueEn: '246 Active Students', valueBn: '২৪৬ জন নিয়মিত শিক্ষার্থী', badge: '2026 Session' },
      { labelEn: 'Female Student Ratio', labelBn: 'ছাত্রী শতকরা হার', valueEn: '54.2% (133 Female)', valueBn: '৫৪.২% (১৩৩ জন ছাত্রী)' },
      { labelEn: 'Male Student Ratio', labelBn: 'ছাত্র শতকরা হার', valueEn: '45.8% (113 Male)', valueBn: '৪৫.৮% (১১৩ জন ছাত্র)' },
      { labelEn: 'Class 6 Enrollment', labelBn: '৬ষ্ঠ শ্রেণি শিক্ষার্থী', valueEn: '118 Students (130 Seats)', valueBn: '১১৮ জন (আসন ১৩০)' },
      { labelEn: 'Class 7 Enrollment', labelBn: '৭ম শ্রেণি শিক্ষার্থী', valueEn: '9 Students (10 Seats)', valueBn: '৯ জন (আসন ১০)' },
      { labelEn: 'Class 8 Enrollment', labelBn: '৮ম শ্রেণি শিক্ষার্থী', valueEn: '8 Students (10 Seats)', valueBn: '৮ জন (আসন ১০)' },
      { labelEn: 'Class 9 Enrollment', labelBn: '৯ম শ্রেণি শিক্ষার্থী', valueEn: '38 Students (Science: 23, Hum: 4, Bus: 11)', valueBn: '৩৮ জন (বিজ্ঞান: ২৩, মানবিক: ৪, ব্যবসায়: ১১)' },
      { labelEn: 'Class 10 Enrollment', labelBn: '১০ম শ্রেণি শিক্ষার্থী', valueEn: '36 Students (40 Seats)', valueBn: '৩৬ জন (আসন ৪০)' },
    ],
    pdfDocuments: [
      { name: 'Student_Demographics_Audit_Report_2026.pdf', fileSize: '1.4 MB', downloadUrl: '#' },
    ],
  },
  {
    key: 'approved-sections',
    number: 4,
    titleEn: '4. Approved Academic Sections & Quotas',
    titleBn: '৪. অনুমোদিত শাখা ও নির্ধারিত আসন সীমা',
    summaryEn: 'Sanctioned sections (Section A & B) and strict enrollment caps per class level.',
    summaryBn: 'অনুমোদিত শাখা (ক ও খ শাখা) এবং শ্রেণিভিত্তিক আসন বণ্টন নীতিমালা।',
    dataItems: [
      { labelEn: 'Class 6 Approved Sections', labelBn: '৬ষ্ঠ শ্রেণি অনুমোদিত শাখা', valueEn: 'Section A & Section B (Cap: 130)', valueBn: 'ক ও খ শাখা (আসন: ১৩০)' },
      { labelEn: 'Class 7 Approved Sections', labelBn: '৭ম শ্রেণি অনুমোদিত শাখা', valueEn: 'Section A (Cap: 10)', valueBn: 'ক শাখা (আসন: ১০)' },
      { labelEn: 'Class 8 Approved Sections', labelBn: '৮ম শ্রেণি অনুমোদিত শাখা', valueEn: 'Section A (Cap: 10)', valueBn: 'ক শাখা (আসন: ১০)' },
      { labelEn: 'Class 9 Science Group', labelBn: '৯ম শ্রেণি বিজ্ঞান বিভাগ', valueEn: 'Section A (Cap: 25 Seats)', valueBn: 'ক শাখা (আসন: ২৫)' },
      { labelEn: 'Class 9 Humanities Group', labelBn: '৯ম শ্রেণি মানবিক বিভাগ', valueEn: 'Section B (Cap: 5 Seats)', valueBn: 'খ শাখা (আসন: ৫)' },
      { labelEn: 'Class 10 Approved Sections', labelBn: '১০ম শ্রেণি অনুমোদিত শাখা', valueEn: 'Section A & B (Cap: 40 Seats)', valueBn: 'ক ও খ শাখা (আসন: ৪০)' },
    ],
    pdfDocuments: [
      { name: 'Board_Approved_Section_Notification.pdf', fileSize: '650 KB', downloadUrl: '#' },
    ],
  },
  {
    key: 'curriculum-routine',
    number: 5,
    titleEn: '5. Curriculum, Routine & Notices',
    titleBn: '৫. পাঠ্যক্রম, শ্রেণি রুটিন ও প্রাতিষ্ঠানিক নোটিশ',
    summaryEn: 'NCTB aligned secondary syllabus, daily 6-period master timetable, exam calendar.',
    summaryBn: 'জাতীয় শিক্ষাক্রম ও পাঠ্যপুস্তক বোর্ড (এনসিটিবি) সিলেবাস ও দৈনিক সময়সূচি।',
    dataItems: [
      { labelEn: 'Curriculum Standard', labelBn: 'পাঠ্যক্রমের মানদণ্ড', valueEn: 'NCTB National Curriculum Standard', valueBn: 'এনসিটিবি জাতীয় শিক্ষাক্রম রূপরেখা' },
      { labelEn: 'Periods per Day', labelBn: 'দৈনিক পিরিয়ড সংখ্যা', valueEn: '6 Active Teaching Periods + Tiffin Break', valueBn: '৬টি পূর্ণাঙ্গ পিরিয়ড ও টিফিন বিরতি' },
      { labelEn: 'Class Timing', labelBn: 'শ্রেণি কার্যক্রমের সময়সূচি', valueEn: '10:00 AM to 04:00 PM (Sat - Thu)', valueBn: 'সকাল ১০:০০ টা হতে বিকাল ৪:০০ টা' },
      { labelEn: 'Co-Curricular Provisions', labelBn: 'সহ-শিক্ষা কার্যক্রম', valueEn: 'Scouting, Girls Guide, Debate, Annual Sports', valueBn: 'স্কাউটিং, গার্ল গাইড, বিতর্ক ও বার্ষিক ক্রীড়া' },
    ],
    pdfDocuments: [
      { name: 'Master_Class_Routine_2026.pdf', fileSize: '1.1 MB', downloadUrl: '#' },
      { name: 'NCTB_Syllabus_Secondary_Classes_6_10.pdf', fileSize: '3.6 MB', downloadUrl: '#' },
    ],
  },
  {
    key: 'mpo-payroll',
    number: 6,
    titleEn: '6. MPO & Payroll Transparency',
    titleBn: '৬. এমপিও ও বেতন কাঠামো স্বচ্ছতা প্রতিবেদন',
    summaryEn: 'Government Monthly Pay Order registry, MPO Code: 8702091302, EFT salary integration.',
    summaryBn: 'সরকারি এমপিও তালিকাভুক্তি, এমপিও কোড: ৮৭০২০৯১৩০২ ও ইএফটি বেতন বিবরণী।',
    dataItems: [
      { labelEn: 'MPO Registration Number', labelBn: 'এমপিও নিবন্ধন নম্বর', valueEn: '8702091302', valueBn: '৮৭০২০৯১৩০২', badge: 'Verified MPO' },
      { labelEn: 'EIIN Master Key', labelBn: 'ইআইআইএন নম্বর', valueEn: '121123', valueBn: '১২১১২৩' },
      { labelEn: 'Sanctioned Teaching Posts', labelBn: 'অনুমোদিত শিক্ষক পদ', valueEn: '12 Sanctioned Posts', valueBn: '১২টি অনুমোদিত পদ' },
      { labelEn: 'Sanctioned Non-Teaching Posts', labelBn: 'অনুমোদিত কর্মচারী পদ', valueEn: '3 Sanctioned Posts', valueBn: '৩টি অনুমোদিত পদ' },
      { labelEn: 'EFT Disbursement Method', labelBn: 'ইএফটি বেতন প্রদান পদ্ধতি', valueEn: 'Direct Bangladesh Bank BEFTN Transfer', valueBn: 'বাংলাদেশ ব্যাংক ইএফটিএন ব্যবস্থা' },
    ],
    pdfDocuments: [
      { name: 'MPO_Sanction_Order_8702091302.pdf', fileSize: '980 KB', downloadUrl: '#' },
      { name: 'EFT_Faculty_Payroll_Register_2026.pdf', fileSize: '1.5 MB', downloadUrl: '#' },
    ],
  },
  {
    key: 'contact-gis',
    number: 7,
    titleEn: '7. Contact & GIS Coordinates',
    titleBn: '৭. যোগাযোগের ঠিকানা ও জিআইএস ভৌগোলিক অবস্থান',
    summaryEn: 'Village Harin Singha, Union Rahmatpur, Gaibandha Sadar, Postcode 5700.',
    summaryBn: 'গ্রাম হরিণ সিংহা, ইউনিয়ন রহমতপুর, গাইবান্ধা সদর, পোস্টকোড ৫৭০০।',
    dataItems: [
      { labelEn: 'Village & Union', labelBn: 'গ্রাম ও ইউনিয়ন', valueEn: 'Harin Singha, Rahmatpur Union', valueBn: 'হরিণ সিংহা, রহমতপুর ইউনিয়ন' },
      { labelEn: 'Upazila & District', labelBn: 'উপজেলা ও জেলা', valueEn: 'Gaibandha Sadar, Gaibandha', valueBn: 'গাইবান্ধা সদর, গাইবান্ধা' },
      { labelEn: 'Division & Postcode', labelBn: 'বিভাগ ও পোস্টকোড', valueEn: 'Rangpur Division, Postcode: 5700', valueBn: 'রংপুর বিভাগ, ডাকঘর: ৫৭০০' },
      { labelEn: 'Official Telephone', labelBn: 'প্রাতিষ্ঠানিক টেলিফোন', valueEn: '+8801309-121123', valueBn: '+৮৮০১৩০৯-১২১১২৩' },
      { labelEn: 'Official Electronic Mail', labelBn: 'প্রাতিষ্ঠানিক ইমেইল', valueEn: 'hsahs121123@gmail.com', valueBn: 'hsahs121123@gmail.com' },
      { labelEn: 'Geo Coordinates', labelBn: 'ভৌগোলিক স্থানাঙ্ক (GIS)', valueEn: '25.3287° N, 89.5412° E (Gaibandha Sadar)', valueBn: '২৫.৩২৮৭° উত্তর, ৮৯.৫৪১২° পূর্ব' },
    ],
    pdfDocuments: [
      { name: 'Campus_GIS_Route_Map.pdf', fileSize: '750 KB', downloadUrl: '#' },
    ],
  },
  {
    key: 'citizen-charter',
    number: 8,
    titleEn: '8. Information Desk (Citizen Charter)',
    titleBn: '৮. তথ্য সেল ও নাগরিক সনদ (সিটিজেন চার্টার)',
    summaryEn: 'Time-bound service delivery commitments for certificates, admissions, and verifications.',
    summaryBn: 'সনদপত্র, প্রত্যয়ন, ভর্তি ও ফলাফল সেবার নির্ধারিত সময়সীমা ও প্রতিশ্রুতি।',
    dataItems: [
      { labelEn: 'Citizen Charter Status', labelBn: 'নাগরিক সনদ স্থিতি', valueEn: 'Enacted & Displayed on Campus / Web', valueBn: 'প্রণীত ও প্রকাশ্যে প্রদর্শিত' },
      { labelEn: 'Designated Information Officer', labelBn: 'দায়িত্বপ্রাপ্ত তথ্য কর্মকর্তা', valueEn: 'Md. Shafiur Rahman (Assistant Headmaster)', valueBn: 'মোঃ শফিউর রহমান (সহকারী প্রধান শিক্ষক)' },
      { labelEn: 'Right to Information (RTI) Cell', labelBn: 'তথ্য অধিকার সেল', valueEn: 'Functional under RTI Act 2009', valueBn: 'তথ্য অধিকার আইন ২০০৯ অনুযায়ী সক্রিয়' },
      { labelEn: 'Service Response Time', labelBn: 'সেবা প্রদানের গড় সময়', valueEn: '1 to 2 Working Days Maximum', valueBn: 'সর্বোচ্চ ১ থেকে ২ কর্মদিবস' },
    ],
    pdfDocuments: [
      { name: 'Citizen_Charter_Notification_HSAHS.pdf', fileSize: '820 KB', downloadUrl: '#' },
    ],
  },
  {
    key: 'grievance-redress',
    number: 9,
    titleEn: '9. Grievance Redress System (GRS)',
    titleBn: '৯. অভিযোগ প্রতিকার ব্যবস্থা (জিআরএস)',
    summaryEn: 'Designated Grievance Redress Officer (GRO), online complaint submission & resolution tracking.',
    summaryBn: 'অভিযোগ প্রতিকার কর্মকর্তা নিয়োগ এবং অনলাইনে অভিযোগ দাখিল ও ট্র্যাকিং সুবিধা।',
    dataItems: [
      { labelEn: 'Designated GRO Officer', labelBn: 'অভিযোগ নিষ্পত্তি কর্মকর্তা', valueEn: 'Md. Ehtashamul Hoque, Assistant Headmaster', valueBn: 'মোঃ এহতেশামুল হক, সহকারী প্রধান শিক্ষক' },
      { labelEn: 'Appellate Authority', labelBn: 'আপিল কর্মকর্তা', valueEn: 'Md. Nazmul Haque Sarker (Headmaster)', valueBn: 'মোঃ নাজমুল হক সরকার (প্রধান শিক্ষক)' },
      { labelEn: 'Standard Resolution SLA', labelBn: 'নিষ্পত্তির সর্বোচ্চ সময়সীমা', valueEn: '7 Working Days from Submission', valueBn: 'দাখিলের ৭ কর্মদিবসের মধ্যে' },
      { labelEn: 'Public Submission Mode', labelBn: 'অভিযোগ দাখিলের মাধ্যম', valueEn: 'Digital Web Portal & Campus Complaint Box', valueBn: 'অনলাইন ওয়েব পোর্টাল ও ক্যাম্পাসের অভিযোগ বাক্স' },
    ],
    pdfDocuments: [
      { name: 'GRS_Operational_Manual_HSAHS.pdf', fileSize: '690 KB', downloadUrl: '#' },
    ],
  },
  {
    key: 'managing-committee',
    number: 10,
    titleEn: '10. Managing Committee Roster',
    titleBn: '১০. বিদ্যালয় পরিচালনা কমিটি (ম্যানেজিং কমিটি)',
    summaryEn: 'Governing body composition, tenure dates, resolutions, and community representatives.',
    summaryBn: 'পরিচালনা পরিষদের সদস্য তালিকা, মেয়াদকাল, রেজুলেশন ও সভাপতি বিবরণ।',
    dataItems: [
      { labelEn: 'Managing Committee President', labelBn: 'কমিটি সভাপতি', valueEn: 'Alhaj Md. Mokhlesur Rahman', valueBn: 'আলহাজ্ব মোঃ মোখলেসুর রহমান' },
      { labelEn: 'Member Secretary', labelBn: 'সদস্য সচিব', valueEn: 'Md. Nazmul Haque Sarker (Headmaster)', valueBn: 'মোঃ নাজমুল হক সরকার (প্রধান শিক্ষক)' },
      { labelEn: 'Approval Order Number', labelBn: 'অনুমোদন স্মারক নম্বর', valueEn: 'DEB/School/Gov/2024/491', valueBn: 'দিনাশিবো/বিদ্যালয়/ম্যাকা/২০২৪/৪৯১' },
      { labelEn: 'Approved Tenure Span', labelBn: 'বর্তমান কমিটির মেয়াদ', valueEn: 'March 2024 to March 2027 (3 Years)', valueBn: 'মার্চ ২০২৪ হতে মার্চ ২০২৭ (৩ বছর)' },
      { labelEn: 'Total Committee Members', labelBn: 'কমিটির মোট সদস্য সংখ্যা', valueEn: '11 Board-Approved Members', valueBn: '১১ জন অনুমোদিত সদস্য' },
    ],
    pdfDocuments: [
      { name: 'Managing_Committee_Board_Approval_Letter.pdf', fileSize: '1.3 MB', downloadUrl: '#' },
      { name: 'Recent_Committee_Resolution_Extracts.pdf', fileSize: '950 KB', downloadUrl: '#' },
    ],
  },
  {
    key: 'faculty-directory',
    number: 11,
    titleEn: '11. Faculty & Staff Directory',
    titleBn: '১১. শিক্ষক ও কর্মচারী জীবনবৃত্তান্ত ও বিবরণী',
    summaryEn: 'Indexed teaching faculty, designations, MPO index numbers, and professional credentials.',
    summaryBn: 'এমপিও ইনডেক্সধারী শিক্ষক-কর্মচারীদের বিবরণ, পদবি ও প্রাতিষ্ঠানিক যোগাযোগ।',
    dataItems: [
      { labelEn: 'Headmaster', labelBn: 'প্রধান শিক্ষক', valueEn: 'Md. Nazmul Haque Sarker (Index: 1048291)', valueBn: 'মোঃ নাজমুল হক সরকার (ইনডেক্স: ১০৪৮২৯১)' },
      { labelEn: 'Assistant Headmaster', labelBn: 'সহকারী প্রধান শিক্ষক', valueEn: 'Md. Shafiur Rahman (Index: 1059382)', valueBn: 'মোঃ শফিউর রহমান (ইনডেক্স: ১০৫৯৩৮২)' },
      { labelEn: 'Assistant Headmaster (Academic)', labelBn: 'সহকারী প্রধান শিক্ষক (একা.)', valueEn: 'Md. Ehtashamul Hoque (Index: 1064719)', valueBn: 'মোঃ এহতেশামুল হক (ইনডেক্স: ১০৬৪৭১৯)' },
      { labelEn: 'Senior Teacher', labelBn: 'সিনিয়র শিক্ষক', valueEn: 'Animesh Chandra Barman (Index: 1078234)', valueBn: 'অনিমেষ চন্দ্র বর্মন (ইনডেক্স: ১০৭৮২৩৪)' },
      { labelEn: 'Assistant Teacher (ICT)', labelBn: 'সহকারী শিক্ষক (আইসিটি)', valueEn: 'K.M. Sohag Rasul (Index: 1091543)', valueBn: 'কে.এম. সোহাগ রসুল (ইনডেক্স: ১০৯১৫৪৩)' },
      { labelEn: 'Senior Teacher (Bangla)', labelBn: 'সিনিয়র শিক্ষক (বাংলা)', valueEn: 'Most. Dilruba Begum (Index: 1082910)', valueBn: 'মোছাঃ দিলরুবা বেগম (ইনডেক্স: ১০৮২৯১০)' },
    ],
    pdfDocuments: [
      { name: 'Faculty_MPO_Index_Register_2026.pdf', fileSize: '1.7 MB', downloadUrl: '#' },
    ],
  },
];

export const CLASS_ROUTINES: ClassRoutineItem[] = [
  { id: 'rt-1', classLevel: 6, section: 'A', day: 'Saturday', periodNumber: 1, timeSlot: '10:00 AM - 10:45 AM', subjectName: 'Bangla 1st Paper', subjectNameBn: 'বাংলা ১ম পত্র', teacherName: 'Most. Dilruba Begum', roomNumber: 'Room 101' },
  { id: 'rt-2', classLevel: 6, section: 'A', day: 'Saturday', periodNumber: 2, timeSlot: '10:45 AM - 11:30 AM', subjectName: 'English 1st Paper', subjectNameBn: 'ইংরেজি ১ম পত্র', teacherName: 'Md. Shafiur Rahman', roomNumber: 'Room 101' },
  { id: 'rt-3', classLevel: 6, section: 'A', day: 'Saturday', periodNumber: 3, timeSlot: '11:30 AM - 12:15 PM', subjectName: 'Mathematics', subjectNameBn: 'গণিত', teacherName: 'Animesh Chandra Barman', roomNumber: 'Room 101' },
  { id: 'rt-4', classLevel: 6, section: 'A', day: 'Saturday', periodNumber: 4, timeSlot: '12:15 PM - 01:00 PM', subjectName: 'General Science', subjectNameBn: 'বিজ্ঞান', teacherName: 'Md. Ehtashamul Hoque', roomNumber: 'Room 101' },
  { id: 'rt-5', classLevel: 6, section: 'A', day: 'Saturday', periodNumber: 5, timeSlot: '01:45 PM - 02:30 PM', subjectName: 'ICT Theory & Practical', subjectNameBn: 'তথ্য ও যোগাযোগ প্রযুক্তি', teacherName: 'K.M. Sohag Rasul', roomNumber: 'Computer Lab' },
  { id: 'rt-6', classLevel: 6, section: 'A', day: 'Saturday', periodNumber: 6, timeSlot: '02:30 PM - 03:15 PM', subjectName: 'Agriculture Studies', subjectNameBn: 'কৃষি শিক্ষা', teacherName: 'Md. Abdur Rahim', roomNumber: 'Room 101' },

  { id: 'rt-7', classLevel: 9, section: 'A', day: 'Sunday', periodNumber: 1, timeSlot: '10:00 AM - 10:45 AM', subjectName: 'Physics', subjectNameBn: 'পদার্থবিজ্ঞান', teacherName: 'Animesh Chandra Barman', roomNumber: 'Room 203' },
  { id: 'rt-8', classLevel: 9, section: 'A', day: 'Sunday', periodNumber: 2, timeSlot: '10:45 AM - 11:30 AM', subjectName: 'Chemistry', subjectNameBn: 'রসায়ন', teacherName: 'Md. Ehtashamul Hoque', roomNumber: 'Room 203' },
  { id: 'rt-9', classLevel: 9, section: 'A', day: 'Sunday', periodNumber: 3, timeSlot: '11:30 AM - 12:15 PM', subjectName: 'Higher Mathematics', subjectNameBn: 'উচ্চতর গণিত', teacherName: 'Md. Nazmul Haque Sarker', roomNumber: 'Room 203' },
  { id: 'rt-10', classLevel: 9, section: 'A', day: 'Sunday', periodNumber: 4, timeSlot: '12:15 PM - 01:00 PM', subjectName: 'English 2nd Paper', subjectNameBn: 'ইংরেজি ২য় পত্র', teacherName: 'Md. Shafiur Rahman', roomNumber: 'Room 203' },
  { id: 'rt-11', classLevel: 9, section: 'A', day: 'Sunday', periodNumber: 5, timeSlot: '01:45 PM - 02:30 PM', subjectName: 'Biology Practical', subjectNameBn: 'জীববিজ্ঞান ব্যবহারিক', teacherName: 'Md. Ehtashamul Hoque', roomNumber: 'Science Lab' },
];
